file:
    /etc/alpine-release:
        exists: true
#        contains: [/^\d+\.\d+\.\d+$/] # switch back if not using edge

command:
    runit-health:
        exit-status: 0

process:
    upstart:
        running: true
    runsvdir:
        running: true
