#!/bin/sh

# Exit on error
set -e

# Terminate function
_term() {
  echo "Caught SIGTERM signal!"
  kill -TERM "$runit_pid" 2>/dev/null
}
trap _term SIGTERM

# Run upstart files
find /etc/upstart -mindepth 1 -maxdepth 1 -type f | sort -n | xargs -n 1 -- sh -c 'echo Running upstart file $0... && $0'

# Run runit
echo Running runit services...
runsvdir -P /etc/service &
runit_pid=$!
wait "$runit_pid"
